POST http://localhost:3000/
Content-Type: application/json

{
  "creditCardNumber": "4242 4242 4242 4242",
  "pin": "756",
  "transactionAmount": 5.0,
  "expirationMonth": "03",
  "expirationYear": "2025"
}
